#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyBack.Android.Tests.Resource", IsApplication=true)]

namespace MoneyBack.Android.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Nunit.Runner.Resource.String.ApplicationName = global::MoneyBack.Android.Tests.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::MoneyBack.Android.Tests.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::MoneyBack.Android.Tests.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::MoneyBack.Android.Tests.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::MoneyBack.Android.Tests.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::MoneyBack.Android.Tests.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int btnPeople = 2130903043;
			
			// aapt resource value: 0x7f030008
			public const int btnPeopleList = 2130903048;
			
			// aapt resource value: 0x7f030007
			public const int btnSavePerson = 2130903047;
			
			// aapt resource value: 0x7f030009
			public const int peopleListTitle = 2130903049;
			
			// aapt resource value: 0x7f030005
			public const int titleLastName = 2130903045;
			
			// aapt resource value: 0x7f030002
			public const int titleMenu = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int titleName = 2130903044;
			
			// aapt resource value: 0x7f030006
			public const int titlePhoneNumber = 2130903046;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
